
services:
  web:
    build:
      context: .
      dockerfile: WordQuestAPI/Dockerfile
    container_name: WordQuestAPI
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=wordquest
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: