// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordQuestAPI.Models;

#nullable disable

namespace WordQuestAPI.Migrations
{
    [DbContext(typeof(WordQuestContext))]
    [Migration("20240525103734_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WordQuestAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_email");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int")
                        .HasColumnName("user_level");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_password");

                    b.Property<int>("UserXP")
                        .HasColumnType("int")
                        .HasColumnName("user_xp");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WordQuestAPI.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("word_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WordId"));

                    b.Property<string>("EnWord")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("en_word");

                    b.Property<string>("FrWord")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fr_word");

                    b.HasKey("WordId");

                    b.ToTable("words");
                });
#pragma warning restore 612, 618
        }
    }
}
